//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trip()
        {
            this.images = new HashSet<image>();
            this.members = new HashSet<member>();
            this.routes = new HashSet<route>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idplace { get; set; }
        public string thumbnail { get; set; }
        public Nullable<System.DateTime> datetogo { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<bool> isfinish { get; set; }
        public Nullable<int> totalrevenue { get; set; }
        public Nullable<int> totalexpend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member> members { get; set; }
        public virtual place place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<route> routes { get; set; }
    }
}
